spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul
    password: Abcd123@
    username: root

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  #      show_sql: true


  profiles:
    include: database, port

logging:
  level:
    org.hibernate.sql: debug